### ISSUE TITLE
overlaybuilder.py error

### ISSUE THREAD

**Issue by RetroGameTalk** [scbroede/dq4-partychat-patcher#4]
```
C:\Python27\python.exe "E:/Desktop/Dragon Quest IV/overlaybuilder.py"
Traceback (most recent call last):
  File "E:/Desktop/Dragon Quest IV/overlaybuilder.py", line 33, in <module>
    overlay.write(bytes("data/param/param_player_talk1.dat", "ascii"))
TypeError: str() takes at most 1 argument (2 given)

Process finished with exit code 1
```

**Comment by RetroGameTalk** [comment]
Also mptpatcher.py:


```
C:\Python27\python.exe "E:/Desktop/Dragon Quest IV/mptpatcher.py"
Patching b0500000.mpt
Traceback (most recent call last):
  File "E:/Desktop/Dragon Quest IV/mptpatcher.py", line 28, in <module>
    value = struct.unpack("<H", pointerTable[i + 4:i + 6])[0]
struct.error: unpack requires a string argument of length 2

Process finished with exit code 1
```

What am i doing wrong?

**Comment by scbroede** [comment]
it looks like you're using python 2.7. those scripts were written for python 3

**Comment by RetroGameTalk** [comment]
ah! sorry thanks!
